### ISSUE TITLE
API endpoint for 6.3 SDKs

### ISSUE THREAD

**Issue by marcprux** [swiftlang/swift-org-website#1256]
SDK CI testing needs an endpoint for 6.3 builds. E.g., we have https://www.swift.org/api/v1/install/dev/6.2/wasm-sdk.json but no https://www.swift.org/api/v1/install/dev/6.3/wasm-sdk.json.

The data seems to be present (e.g., https://github.com/swiftlang/swift-org-website/blob/main/_data/builds/swift-6_3-branch/wasm-sdk.yml), so I'm hopeful that this will just need a new folder in https://github.com/swiftlang/swift-org-website/tree/main/api/v1/install/dev for 6.3.

**Comment by kkebo** [comment]
This issue should have been resolved by the PR https://github.com/swiftlang/swift-org-website/pull/1257.

**Comment by kkebo** [comment]
@czechboy0 What doc do you mean?

~~https://www.swift.org/openapi/swiftorg.yaml doesn't need to be updated because it doesn't contain version numbers hardcoded.~~

And https://www.swift.org/api/v1/install/dev/6.3/wasm-sdk.json is now available thanks to #1257.

**Comment by marcprux** [comment]
The endpoint I need (https://www.swift.org/api/v1/install/dev/6.3/android-sdk.json) is now available. Thanks!

The OpenAPI doc still isn't updated, so I'll leave this issue open (even though I'm not really sure what [`KnownSourceBranch`](https://github.com/swiftlang/swift-org-website/blob/main/openapi/swiftorg.yaml#L253C5-L253C22) is used for).

**Comment by kkebo** [comment]
I understand now. Thank you for clarifying.
